# Generated by Django 4.0.5 on 2022-06-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_coffee_merchant_user_delete_choice_delete_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffee',
            name='is_it_available',
        ),
        migrations.AddField(
            model_name='coffee',
            name='how_many_are_available',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='mail',
            field=models.EmailField(default=2, max_length=254),
            preserve_default=False,
        ),
    ]
