# Generated by Django 4.0.5 on 2022-06-14 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_remove_coffee_is_it_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='is_it_available',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='coffee',
            name='is_it_speciality',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='coffee',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='coffee',
            name='origin',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='coffee',
            name='producer',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='coffee',
            name='producer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.merchant'),
        ),
        migrations.AddField(
            model_name='coffee',
            name='toast_level',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='country_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='how_many_are_available',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='admin_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.user'),
        ),
    ]
