# Generated by Django 4.0.5 on 2022-06-14 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_coffee_is_it_available_coffee_is_it_speciality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='merchant_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='country_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mail',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
