# Generated by Django 4.0.5 on 2022-06-14 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_rename_origin_coffee_origin_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='origin_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='process_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
