# Generated by Django 4.0.5 on 2022-06-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_alter_coffee_origin_2_alter_coffee_process_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('origin', models.CharField(max_length=100)),
                ('taste_profile', models.CharField(max_length=100)),
            ],
        ),
    ]
