# Generated by Django 4.0.5 on 2022-06-24 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_remove_coffeetypes_taste_profile_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CoffeeTypes',
            new_name='CoffeeType',
        ),
    ]
