# Generated by Django 4.0.5 on 2022-06-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_rename_coffeetypes_coffeetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
