# Generated by Django 4.0.5 on 2022-06-26 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_merchant_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='url_to_product',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='how_many_are_available',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='producer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='tasting_notes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='toast_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='varieties',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.coffeetype'),
        ),
    ]
