# Generated by Django 4.0.5 on 2022-06-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_rename_origin_1_coffee_origin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='url_to_product',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
