# Generated by Django 4.0.5 on 2022-06-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_alter_coffee_url_to_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='green_coffee',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='coffee',
            name='green_coffee_2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='coffee',
            name='origin_2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='coffee',
            name='process_2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='coffee',
            name='producer_2',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
