# Generated by Django 4.0.5 on 2022-06-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_rename_green_coffee_coffee_origin_area_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='CoffeeType',
            new_name='CoffeePlantType',
        ),
    ]
