# Generated by Django 4.0.5 on 2022-06-26 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_process_rename_coffeetype_coffeeplanttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='process',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_process', to='polls.process'),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='process_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.process'),
        ),
    ]
