# Generated by Django 4.0.5 on 2022-06-26 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_alter_coffee_process_alter_coffee_process_2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='process',
            options={'verbose_name_plural': 'Processes'},
        ),
    ]
