# Generated by Django 4.0.5 on 2022-06-28 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_alter_process_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffee',
            name='process_2',
        ),
        migrations.RemoveField(
            model_name='coffee',
            name='process',
        ),
        migrations.AddField(
            model_name='coffee',
            name='process',
            field=models.ManyToManyField(null=True, to='polls.process'),
        ),
    ]
