# Generated by Django 4.0.5 on 2022-06-28 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_remove_coffee_process_2_remove_coffee_process_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='process',
            field=models.ManyToManyField(to='polls.process'),
        ),
    ]
