# Generated by Django 4.0.5 on 2022-06-28 14:04

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0023_alter_coffee_origin_area_alter_coffee_origin_area_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country_code',
            field=django_countries.fields.CountryField(max_length=746, multiple=True),
        ),
    ]
