# Generated by Django 4.0.5 on 2022-06-28 14:09

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0024_alter_user_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country_code',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
