# Generated by Django 4.0.5 on 2022-10-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_user_userprofile_alter_merchant_admin_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='image_coffee',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
