# Generated by Django 4.0.5 on 2022-11-01 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_image_coffee_coffee_coffee_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='admin_id',
        ),
        migrations.DeleteModel(
            name='Coffee',
        ),
        migrations.DeleteModel(
            name='CoffeePlantType',
        ),
        migrations.DeleteModel(
            name='Merchant',
        ),
        migrations.DeleteModel(
            name='Process',
        ),
    ]
