# Generated by Django 4.0.5 on 2022-11-01 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeePlantType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('origin', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'Processes',
            },
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.IntegerField(null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('merchant_name', models.CharField(max_length=200, null=True)),
                ('admin_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('producer', models.CharField(blank=True, max_length=200, null=True)),
                ('producer_2', models.CharField(blank=True, max_length=200, null=True)),
                ('seller', models.CharField(max_length=200, null=True)),
                ('origin_country', models.CharField(max_length=200, null=True)),
                ('origin_country_2', models.CharField(blank=True, max_length=200, null=True)),
                ('origin_area', models.CharField(blank=True, max_length=200, null=True)),
                ('origin_area_2', models.CharField(blank=True, max_length=200, null=True)),
                ('tasting_notes', models.CharField(blank=True, max_length=200, null=True)),
                ('is_it_speciality', models.BooleanField(null=True)),
                ('toast_level', models.IntegerField(blank=True, null=True)),
                ('is_it_available', models.BooleanField(null=True)),
                ('how_many_are_available', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('url_to_product', models.CharField(max_length=100, null=True)),
                ('coffee_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('process', models.ManyToManyField(to='public.process')),
                ('seller_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='public.merchant')),
                ('varieties', models.ManyToManyField(to='public.coffeeplanttype')),
            ],
        ),
    ]
