# Generated by Django 4.0.5 on 2022-11-01 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0006_alter_coffee_coffee_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
