# Generated by Django 4.0.5 on 2022-11-01 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0007_coffee_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
