# Generated by Django 4.0.5 on 2022-12-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0008_alter_coffee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='coffee_image',
            field=models.ImageField(blank=True, null=True, upload_to='Progetto/static/theme/assets/img/Coffee/'),
        ),
    ]
